# cargo                                                             :Scratch:

# [[file:~/Workspace/Programming/rust-libs/rust-liblbfgs/lbfgs.note::*cargo][cargo:1]]
[package]
name = "liblbfgs"
version = "0.0.1"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
libc = "*"

[build-dependencies]
bindgen = "0.26.3"
# cargo:1 ends here
